apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: frontend
  namespace: staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  strategy:
    blueGreen:
      activeService: frontend-active
      previewService: frontend-preview
      autoPromotionEnabled: true

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend:6c9608ab4342622e3bb8df2605025703142cd304
        imagePullPolicy: Always
        ports:
        - containerPort: 80