apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: frontend
  namespace: staging

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  strategy:
    blueGreen:
      activeService: frontend-active
      previewService: frontend-preview
      autoPromotionEnabled: false    

  template:
    metadata:
      labels:
        app: frontend

  spec:
  containers:
    - name: frontend
      image: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend:3a135c03452f64b222a68589a1d8b8b050e10ed0
      imagePullPolicy: Always
      ports:
        - containerPort: 80