apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- namespace.yaml
- secret.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-rollout.yaml
- frontend-active-service.yaml
- frontend-preview-service.yaml
- ingress.yaml
  
images:
- name: capstone-backend
  newName: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-backend
  newTag: efe8d764ecfcb0654a643441315bf38f0ddff5e1
- name: capstone-frontend
  newName: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend
  newTag: efe8d764ecfcb0654a643441315bf38f0ddff5e1
