apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- namespace.yaml
- secret.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-active-service.yaml
- frontend-service.yaml
- ingress.yaml

images:
- name: capstone-backend
  newName: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-backend
  newTag: c7dbab33c8712e0edc443aef71d953eb76328d5e
- name: capstone-frontend
  newName: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend
  newTag: c7dbab33c8712e0edc443aef71d953eb76328d5e
