apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- frontend-deployment.yaml
- backend-service.yaml
- frontend-service.yaml


images:
- name: capstone-backend
  newName: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-backend
  newTag: 13f5ce82e88ee57322f1a3aba0d98ac7944e9845
- name: capstone-frontend
  newName: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend
  newTag: 13f5ce82e88ee57322f1a3aba0d98ac7944e9845
