apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 0f49fcd7a8fab642f9644e0a4d67b9f2bf9ce3e2cbf1f2ebfa7a301dbd59a7e0
  creationTimestamp: "2026-06-25T09:02:29Z"
  generateName: promtail-
  generation: 1
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
    controller-revision-hash: 66cb56d6f8
    pod-template-generation: "1"
  name: promtail-6h5wv
  namespace: monitoring
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: promtail
    uid: 16b2f90a-eb20-4e4d-8095-359f99c06069
  resourceVersion: "339030"
  uid: 5810fe6b-0f37-4a10-97e4-64ea743db40a
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-10-0-4-123.us-east-2.compute.internal
  automountServiceAccountToken: true
  containers:
  - args:
    - -config.file=/etc/promtail/promtail.yaml
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: docker.io/grafana/promtail:3.5.1
    imagePullPolicy: IfNotPresent
    name: promtail
    ports:
    - containerPort: 3101
      name: http-metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /ready
        port: http-metrics
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/promtail
      name: config
    - mountPath: /run/promtail
      name: run
    - mountPath: /var/lib/docker/containers
      name: containers
      readOnly: true
    - mountPath: /var/log/pods
      name: pods
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-plgdx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsGroup: 0
    runAsUser: 0
  serviceAccount: promtail
  serviceAccountName: promtail
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - name: config
    secret:
      defaultMode: 420
      secretName: promtail
  - hostPath:
      path: /run/promtail
      type: ""
    name: run
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: containers
  - hostPath:
      path: /var/log/pods
      type: ""
    name: pods
  - name: kube-api-access-plgdx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-25T09:02:29Z"
    message: '0/3 nodes are available: 1 Too many pods, 2 node(s) didn''t satisfy
      plugin(s) [NodeAffinity]. preemption: 0/3 nodes are available: 1 No preemption
      victims found for incoming pod, 2 Preemption is not helpful for scheduling.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
