apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: production

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend:138a975544b6648b89a4bea6052bf9f6ac0f33f1

        imagePullPolicy: Always

        ports:
        - containerPort: 80