apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: production

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-frontend:dbfead44719fab98b3b3ba0f0683471cbe0c581a

        imagePullPolicy: Always

        ports:
        - containerPort: 80