apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- namespace.yaml
- secret.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml


images:
- name: capstone-backend
  newName: 622488711452.dkr.ecr.us-east-2.amazonaws.com/capstone-backend
  newTag: 6661eac8ba8abf1f1092495685bc2557dd79d357
- name: capstone-frontend
  newName: image
