spec:
  source:
    repoURL: https://github.com/MYISHATASNEEMSHAFI/capstone_project.git
    targetRevision: master
    path: kubernetes/staging
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  spec:
  ignoreDifferences:
    - group: ""
      kind: Service
      name: frontend-active-service
      namespace: staging
      jsonPointers:
        - /spec/selector

    - group: ""
      kind: Service
      name: frontend-deployment
      namespace: staging
      jsonPointers:
        - /spec/selector    