name: Build, Push and Update Manifests

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:

    #################################################
    # Checkout Repository
    #################################################

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #################################################
    # Setup Java
    #################################################

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    #################################################
    # Build Backend
    #################################################

    - name: Build Backend
      working-directory: backend
      run: mvn clean package -DskipTests

    #################################################
    # Setup Node
    #################################################

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    #################################################
    # Build Frontend
    #################################################

    - name: Install Frontend Packages
      working-directory: frontend
      run: npm install

    - name: Build Frontend
      working-directory: frontend
      run: npm run build

    #################################################
    # Configure AWS
    #################################################

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    #################################################
    # Login to Amazon ECR
    #################################################

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    #################################################
    # Build Backend Image
    #################################################

    - name: Build Backend Docker Image
      run: |
        docker build \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-backend:$IMAGE_TAG \
        ./backend

    #################################################
    # Build Frontend Image
    #################################################

    - name: Build Frontend Docker Image
      run: |
        docker build \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-frontend:$IMAGE_TAG \
        ./frontend

    #################################################
    # Install Trivy
    #################################################

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
        chmod +x install.sh
        sudo ./install.sh -b /usr/local/bin

    - name: Verify Trivy
      run: trivy --version


          #################################################
    # Scan Backend Image
    #################################################

    - name: Scan Backend Image
      run: |
        trivy image \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0 \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-backend:$IMAGE_TAG

    #################################################
    # Scan Frontend Image
    #################################################

    - name: Scan Frontend Image
      run: |
        trivy image \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0 \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-frontend:$IMAGE_TAG

    #################################################
    # Push Backend Image
    #################################################

    - name: Push Backend Image
      run: |
        docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-backend:$IMAGE_TAG

    #################################################
    # Push Frontend Image
    #################################################

    - name: Push Frontend Image
      run: |
        docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-frontend:$IMAGE_TAG

    #################################################
    # Install Kustomize
    #################################################

    - name: Install Kustomize
      run: |
        curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
        sudo mv kustomize /usr/local/bin/

    #################################################
    # Update Kustomization Images
    #################################################

    - name: Update Kustomization
      run: |
        cd kubernetes/staging

        kustomize edit set image \
        capstone-backend=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-backend:$IMAGE_TAG

        kustomize edit set image \
        capstone-frontend=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone-frontend:$IMAGE_TAG

    #################################################
    # Commit Manifest Changes
    #################################################

    - name: Commit Updated Manifest
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git add kubernetes/staging/kustomization.yaml

        git diff --cached --quiet && echo "Nothing to commit" && exit 0

        git commit -m "Update staging images to $IMAGE_TAG"

        git push origin master