name: Promote to Production

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ########################################################
      # Read image tags from staging manifests
      ########################################################

      - name: Read Backend Image
        run: |
              BACKEND_IMAGE=$(awk '/image:/{print $2; exit}' kubernetes/staging/backend-deployment.yaml)

              if [ -z "$BACKEND_IMAGE" ]; then
                echo "backend image not found!"
                exit 1
              fi
              echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV
     
      - name: Read Frontend Image
        run: |
            FRONTEND_IMAGE=$(awk '/image:/{print $2; exit}' kubernetes/staging/frontend-deployment.yaml)

            if [ -z "$FRONTEND_IMAGE" ]; then
              echo "Frontend image not found!"
              exit 1
            fi

            echo "FRONTEND_IMAGE=$FRONTEND_IMAGE" >> $GITHUB_ENV
   
      ########################################################
      # Update production manifests
      ########################################################

      - name: Update Backend Manifest
        run: |
          sed -i "s|image:.*|image: ${BACKEND_IMAGE}|g" kubernetes/production/backend-deployment.yaml

      - name: Update Frontend Manifest
        run: |
          sed -i "s|image:.*|image: ${FRONTEND_IMAGE}|g" kubernetes/production/frontend-deployment.yaml

      ########################################################
      # Commit changes
      ########################################################

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kubernetes/production/backend-deployment.yaml
          git add kubernetes/production/frontend-deployment.yaml

          git commit -m "Promote staging images to production" || echo "No changes"

          git push