name: Promote to Production

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy image tags from staging to production
        run: |
          BACKEND_TAG=$(grep -A2 "name: capstone-backend" kubernetes/staging/kustomization.yaml | grep newTag | awk '{print $2}')
          FRONTEND_TAG=$(grep -A2 "name: capstone-frontend" kubernetes/staging/kustomization.yaml | grep newTag | awk '{print $2}')

          sed -i "/name: capstone-backend/{n;n;s|newTag:.*|newTag: ${BACKEND_TAG}|;}" kubernetes/production/kustomization.yaml
          sed -i "/name: capstone-frontend/{n;n;s|newTag:.*|newTag: ${FRONTEND_TAG}|;}" kubernetes/production/kustomization.yaml

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kubernetes/production/kustomization.yaml

          git diff --cached --quiet && exit 0

          git commit -m "Promote staging images to production"

          git push origin master